name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Pack
        run: dotnet pack
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: MoeDevelops.XmlFileLib/bin/Release/*.nupkg
      - name: Publish
        run: dotnet nuget push MoeDevelops.XmlFileLib/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json