name: Release

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Release
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: MoeDevelops.XmlFileLib/MoeDevelops.XmlFileLib.csproj
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: MoeDevelops.XmlFileLib/bin/Release/*.nupkg
